function [matriz,bc]=prodinterno(classeelementos)
    % Função responsável por criar a matriz K de cada elemento, por meio do
    % produto interno da forma <(bi,ci),(bj,cj)> para os elementos kij
    bc=[classeelementos.no2posy-classeelementos.no3posy...
        classeelementos.no3posx-classeelementos.no2posx;...
        classeelementos.no3posy-classeelementos.no1posy...
        classeelementos.no1posx-classeelementos.no3posx;...
        classeelementos.no1posy-classeelementos.no2posy...
        classeelementos.no2posx-classeelementos.no1posx];
    matriz=bc*bc';
end